// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/spf13/viper"
	"shiliu/internal/repository"
	"shiliu/internal/server"
	"shiliu/internal/service"
	"shiliu/internal/task"
	"shiliu/pkg/app"
	"shiliu/pkg/jwt"
	"shiliu/pkg/log"
	"shiliu/pkg/sid"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	db := repository.NewDB(viperViper, logger)
	repositoryRepository := repository.NewRepository(logger, db)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	taskTask := task.NewTask(transaction, logger, sidSid)
	jwtJWT := jwt.NewJwt(viperViper)
	serviceService := service.NewService(transaction, logger, sidSid, jwtJWT)
	feedRepository := repository.NewFeedRepository(repositoryRepository)
	contentItemRepository := repository.NewContentItemRepository(repositoryRepository)
	fetcher := service.NewDefaultFetcher()
	feedService := service.NewFeedService(serviceService, feedRepository, contentItemRepository, fetcher)
	feedTask := task.NewFeedTask(taskTask, feedService)
	autoSummaryConfigRepository := repository.NewAutoSummaryConfigRepository(repositoryRepository)
	aiServiceConfigRepository := repository.NewAIServiceConfigRepository(repositoryRepository)
	chatCompletion := service.NewDefaultChatCompletion()
	contentItemService := service.NewContentItemService(serviceService, contentItemRepository, aiServiceConfigRepository, chatCompletion)
	autoSummaryService := service.NewAutoSummaryService(serviceService, autoSummaryConfigRepository, contentItemRepository, contentItemService)
	autoSummaryTask := task.NewAutoSummaryTask(taskTask, autoSummaryService)
	taskServer := server.NewTaskServer(logger, viperViper, feedTask, autoSummaryTask)
	appApp := newApp(taskServer)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewTransaction, repository.NewFeedRepository, repository.NewContentItemRepository, repository.NewAIServiceConfigRepository, repository.NewAutoSummaryConfigRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewDefaultFetcher, service.NewFeedService, service.NewDefaultChatCompletion, service.NewContentItemService, service.NewAutoSummaryService)

var taskSet = wire.NewSet(task.NewTask, task.NewFeedTask, task.NewAutoSummaryTask)

var serverSet = wire.NewSet(server.NewTaskServer)

// build App
func newApp(task2 *server.TaskServer,
) *app.App {
	return app.NewApp(app.WithServer(task2), app.WithName("shiliu-task"))
}
