// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/content_item.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"
	model "shiliu/internal/model"
	repository "shiliu/internal/repository"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockContentItemRepository is a mock of ContentItemRepository interface.
type MockContentItemRepository struct {
	ctrl     *gomock.Controller
	recorder *MockContentItemRepositoryMockRecorder
}

// MockContentItemRepositoryMockRecorder is the mock recorder for MockContentItemRepository.
type MockContentItemRepositoryMockRecorder struct {
	mock *MockContentItemRepository
}

// NewMockContentItemRepository creates a new mock instance.
func NewMockContentItemRepository(ctrl *gomock.Controller) *MockContentItemRepository {
	mock := &MockContentItemRepository{ctrl: ctrl}
	mock.recorder = &MockContentItemRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContentItemRepository) EXPECT() *MockContentItemRepositoryMockRecorder {
	return m.recorder
}

// AssignTags mocks base method.
func (m *MockContentItemRepository) AssignTags(ctx context.Context, itemID uint, tagIDs []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignTags", ctx, itemID, tagIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignTags indicates an expected call of AssignTags.
func (mr *MockContentItemRepositoryMockRecorder) AssignTags(ctx, itemID, tagIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignTags", reflect.TypeOf((*MockContentItemRepository)(nil).AssignTags), ctx, itemID, tagIDs)
}

// ClaimAISummary mocks base method.
func (m *MockContentItemRepository) ClaimAISummary(ctx context.Context, itemID uint, allowedStatuses []model.AISummaryStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimAISummary", ctx, itemID, allowedStatuses)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClaimAISummary indicates an expected call of ClaimAISummary.
func (mr *MockContentItemRepositoryMockRecorder) ClaimAISummary(ctx, itemID, allowedStatuses interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimAISummary", reflect.TypeOf((*MockContentItemRepository)(nil).ClaimAISummary), ctx, itemID, allowedStatuses)
}

// Create mocks base method.
func (m *MockContentItemRepository) Create(ctx context.Context, item *model.ContentItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockContentItemRepositoryMockRecorder) Create(ctx, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockContentItemRepository)(nil).Create), ctx, item)
}

// GetByFeedAndDedupeKey mocks base method.
func (m *MockContentItemRepository) GetByFeedAndDedupeKey(ctx context.Context, feedID uint, dedupeKey string) (*model.ContentItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByFeedAndDedupeKey", ctx, feedID, dedupeKey)
	ret0, _ := ret[0].(*model.ContentItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByFeedAndDedupeKey indicates an expected call of GetByFeedAndDedupeKey.
func (mr *MockContentItemRepositoryMockRecorder) GetByFeedAndDedupeKey(ctx, feedID, dedupeKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByFeedAndDedupeKey", reflect.TypeOf((*MockContentItemRepository)(nil).GetByFeedAndDedupeKey), ctx, feedID, dedupeKey)
}

// GetByID mocks base method.
func (m *MockContentItemRepository) GetByID(ctx context.Context, id uint) (*model.ContentItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.ContentItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockContentItemRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockContentItemRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockContentItemRepository) List(ctx context.Context, filter repository.ContentItemListFilter, limit, offset int) ([]*model.ContentItem, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter, limit, offset)
	ret0, _ := ret[0].([]*model.ContentItem)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockContentItemRepositoryMockRecorder) List(ctx, filter, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockContentItemRepository)(nil).List), ctx, filter, limit, offset)
}

// ListAutoSummaryCandidates mocks base method.
func (m *MockContentItemRepository) ListAutoSummaryCandidates(ctx context.Context, filter repository.AutoSummaryCandidateFilter, limit int) ([]*model.ContentItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAutoSummaryCandidates", ctx, filter, limit)
	ret0, _ := ret[0].([]*model.ContentItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAutoSummaryCandidates indicates an expected call of ListAutoSummaryCandidates.
func (mr *MockContentItemRepositoryMockRecorder) ListAutoSummaryCandidates(ctx, filter, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAutoSummaryCandidates", reflect.TypeOf((*MockContentItemRepository)(nil).ListAutoSummaryCandidates), ctx, filter, limit)
}

// ListByFeedID mocks base method.
func (m *MockContentItemRepository) ListByFeedID(ctx context.Context, feedID uint, limit int) ([]*model.ContentItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByFeedID", ctx, feedID, limit)
	ret0, _ := ret[0].([]*model.ContentItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByFeedID indicates an expected call of ListByFeedID.
func (mr *MockContentItemRepositoryMockRecorder) ListByFeedID(ctx, feedID, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByFeedID", reflect.TypeOf((*MockContentItemRepository)(nil).ListByFeedID), ctx, feedID, limit)
}

// RemoveTags mocks base method.
func (m *MockContentItemRepository) RemoveTags(ctx context.Context, itemID uint, tagIDs []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTags", ctx, itemID, tagIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveTags indicates an expected call of RemoveTags.
func (mr *MockContentItemRepositoryMockRecorder) RemoveTags(ctx, itemID, tagIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTags", reflect.TypeOf((*MockContentItemRepository)(nil).RemoveTags), ctx, itemID, tagIDs)
}

// UpdateAISummary mocks base method.
func (m *MockContentItemRepository) UpdateAISummary(ctx context.Context, itemID uint, status model.AISummaryStatus, markdown string, generatedAt *time.Time, summaryError string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAISummary", ctx, itemID, status, markdown, generatedAt, summaryError)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAISummary indicates an expected call of UpdateAISummary.
func (mr *MockContentItemRepositoryMockRecorder) UpdateAISummary(ctx, itemID, status, markdown, generatedAt, summaryError interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAISummary", reflect.TypeOf((*MockContentItemRepository)(nil).UpdateAISummary), ctx, itemID, status, markdown, generatedAt, summaryError)
}

// UpdateAISummarySearchText mocks base method.
func (m *MockContentItemRepository) UpdateAISummarySearchText(ctx context.Context, itemID uint, markdown string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAISummarySearchText", ctx, itemID, markdown)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAISummarySearchText indicates an expected call of UpdateAISummarySearchText.
func (mr *MockContentItemRepositoryMockRecorder) UpdateAISummarySearchText(ctx, itemID, markdown interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAISummarySearchText", reflect.TypeOf((*MockContentItemRepository)(nil).UpdateAISummarySearchText), ctx, itemID, markdown)
}

// UpdateAudioProgress mocks base method.
func (m *MockContentItemRepository) UpdateAudioProgress(ctx context.Context, itemID uint, progressSeconds int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAudioProgress", ctx, itemID, progressSeconds)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAudioProgress indicates an expected call of UpdateAudioProgress.
func (mr *MockContentItemRepositoryMockRecorder) UpdateAudioProgress(ctx, itemID, progressSeconds interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAudioProgress", reflect.TypeOf((*MockContentItemRepository)(nil).UpdateAudioProgress), ctx, itemID, progressSeconds)
}

// UpdateMark mocks base method.
func (m *MockContentItemRepository) UpdateMark(ctx context.Context, itemID uint, mark model.ContentItemMark, marked bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMark", ctx, itemID, mark, marked)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMark indicates an expected call of UpdateMark.
func (mr *MockContentItemRepositoryMockRecorder) UpdateMark(ctx, itemID, mark, marked interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMark", reflect.TypeOf((*MockContentItemRepository)(nil).UpdateMark), ctx, itemID, mark, marked)
}

// UpdateProcessingStatus mocks base method.
func (m *MockContentItemRepository) UpdateProcessingStatus(ctx context.Context, itemID uint, status model.ContentItemProcessingStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProcessingStatus", ctx, itemID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProcessingStatus indicates an expected call of UpdateProcessingStatus.
func (mr *MockContentItemRepositoryMockRecorder) UpdateProcessingStatus(ctx, itemID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProcessingStatus", reflect.TypeOf((*MockContentItemRepository)(nil).UpdateProcessingStatus), ctx, itemID, status)
}

// UpdateSearchText mocks base method.
func (m *MockContentItemRepository) UpdateSearchText(ctx context.Context, itemID uint, title, availableText string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSearchText", ctx, itemID, title, availableText)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSearchText indicates an expected call of UpdateSearchText.
func (mr *MockContentItemRepositoryMockRecorder) UpdateSearchText(ctx, itemID, title, availableText interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSearchText", reflect.TypeOf((*MockContentItemRepository)(nil).UpdateSearchText), ctx, itemID, title, availableText)
}
