// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/content_item.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"
	model "shiliu/internal/model"
	repository "shiliu/internal/repository"

	gomock "github.com/golang/mock/gomock"
)

// MockContentItemRepository is a mock of ContentItemRepository interface.
type MockContentItemRepository struct {
	ctrl     *gomock.Controller
	recorder *MockContentItemRepositoryMockRecorder
}

// MockContentItemRepositoryMockRecorder is the mock recorder for MockContentItemRepository.
type MockContentItemRepositoryMockRecorder struct {
	mock *MockContentItemRepository
}

// NewMockContentItemRepository creates a new mock instance.
func NewMockContentItemRepository(ctrl *gomock.Controller) *MockContentItemRepository {
	mock := &MockContentItemRepository{ctrl: ctrl}
	mock.recorder = &MockContentItemRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContentItemRepository) EXPECT() *MockContentItemRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockContentItemRepository) Create(ctx context.Context, item *model.ContentItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockContentItemRepositoryMockRecorder) Create(ctx, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockContentItemRepository)(nil).Create), ctx, item)
}

// GetByFeedAndDedupeKey mocks base method.
func (m *MockContentItemRepository) GetByFeedAndDedupeKey(ctx context.Context, feedID uint, dedupeKey string) (*model.ContentItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByFeedAndDedupeKey", ctx, feedID, dedupeKey)
	ret0, _ := ret[0].(*model.ContentItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByFeedAndDedupeKey indicates an expected call of GetByFeedAndDedupeKey.
func (mr *MockContentItemRepositoryMockRecorder) GetByFeedAndDedupeKey(ctx, feedID, dedupeKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByFeedAndDedupeKey", reflect.TypeOf((*MockContentItemRepository)(nil).GetByFeedAndDedupeKey), ctx, feedID, dedupeKey)
}

// GetByID mocks base method.
func (m *MockContentItemRepository) GetByID(ctx context.Context, id uint) (*model.ContentItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.ContentItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockContentItemRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockContentItemRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockContentItemRepository) List(ctx context.Context, filter repository.ContentItemListFilter, limit, offset int) ([]*model.ContentItem, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter, limit, offset)
	ret0, _ := ret[0].([]*model.ContentItem)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockContentItemRepositoryMockRecorder) List(ctx, filter, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockContentItemRepository)(nil).List), ctx, filter, limit, offset)
}

// ListByFeedID mocks base method.
func (m *MockContentItemRepository) ListByFeedID(ctx context.Context, feedID uint, limit int) ([]*model.ContentItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByFeedID", ctx, feedID, limit)
	ret0, _ := ret[0].([]*model.ContentItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByFeedID indicates an expected call of ListByFeedID.
func (mr *MockContentItemRepositoryMockRecorder) ListByFeedID(ctx, feedID, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByFeedID", reflect.TypeOf((*MockContentItemRepository)(nil).ListByFeedID), ctx, feedID, limit)
}

// UpdateAudioProgress mocks base method.
func (m *MockContentItemRepository) UpdateAudioProgress(ctx context.Context, itemID uint, progressSeconds int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAudioProgress", ctx, itemID, progressSeconds)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAudioProgress indicates an expected call of UpdateAudioProgress.
func (mr *MockContentItemRepositoryMockRecorder) UpdateAudioProgress(ctx, itemID, progressSeconds interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAudioProgress", reflect.TypeOf((*MockContentItemRepository)(nil).UpdateAudioProgress), ctx, itemID, progressSeconds)
}

// UpdateMark mocks base method.
func (m *MockContentItemRepository) UpdateMark(ctx context.Context, itemID uint, mark model.ContentItemMark, marked bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMark", ctx, itemID, mark, marked)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMark indicates an expected call of UpdateMark.
func (mr *MockContentItemRepositoryMockRecorder) UpdateMark(ctx, itemID, mark, marked interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMark", reflect.TypeOf((*MockContentItemRepository)(nil).UpdateMark), ctx, itemID, mark, marked)
}

// UpdateProcessingStatus mocks base method.
func (m *MockContentItemRepository) UpdateProcessingStatus(ctx context.Context, itemID uint, status model.ContentItemProcessingStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProcessingStatus", ctx, itemID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProcessingStatus indicates an expected call of UpdateProcessingStatus.
func (mr *MockContentItemRepositoryMockRecorder) UpdateProcessingStatus(ctx, itemID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProcessingStatus", reflect.TypeOf((*MockContentItemRepository)(nil).UpdateProcessingStatus), ctx, itemID, status)
}
