// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/spf13/viper"
	"shiliu/internal/handler"
	"shiliu/internal/job"
	"shiliu/internal/repository"
	"shiliu/internal/router"
	"shiliu/internal/server"
	"shiliu/internal/service"
	"shiliu/pkg/app"
	"shiliu/pkg/jwt"
	"shiliu/pkg/log"
	"shiliu/pkg/server/http"
	"shiliu/pkg/sid"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	handlerHandler := handler.NewHandler(logger)
	db := repository.NewDB(viperViper, logger)
	repositoryRepository := repository.NewRepository(logger, db)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	serviceService := service.NewService(transaction, logger, sidSid, jwtJWT)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	feedRepository := repository.NewFeedRepository(repositoryRepository)
	contentItemRepository := repository.NewContentItemRepository(repositoryRepository)
	fetcher := service.NewDefaultFetcher()
	feedService := service.NewFeedService(serviceService, feedRepository, contentItemRepository, fetcher)
	feedHandler := handler.NewFeedHandler(handlerHandler, feedService)
	contentItemService := service.NewContentItemService(serviceService, contentItemRepository)
	contentItemHandler := handler.NewContentItemHandler(handlerHandler, contentItemService)
	tagRepository := repository.NewTagRepository(repositoryRepository)
	tagService := service.NewTagService(serviceService, tagRepository, contentItemRepository)
	tagHandler := handler.NewTagHandler(handlerHandler, tagService)
	folderRepository := repository.NewFolderRepository(repositoryRepository)
	folderService := service.NewFolderService(serviceService, folderRepository, feedRepository)
	folderHandler := handler.NewFolderHandler(handlerHandler, folderService)
	routerDeps := router.RouterDeps{
		Logger:             logger,
		Config:             viperViper,
		JWT:                jwtJWT,
		UserHandler:        userHandler,
		FeedHandler:        feedHandler,
		ContentItemHandler: contentItemHandler,
		TagHandler:         tagHandler,
		FolderHandler:      folderHandler,
	}
	httpServer := server.NewHTTPServer(routerDeps)
	jobJob := job.NewJob(transaction, logger, sidSid)
	userJob := job.NewUserJob(jobJob, userRepository)
	jobServer := server.NewJobServer(logger, userJob)
	appApp := newApp(httpServer, jobServer)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewTransaction, repository.NewUserRepository, repository.NewFeedRepository, repository.NewContentItemRepository, repository.NewTagRepository, repository.NewFolderRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewDefaultFetcher, service.NewFeedService, service.NewFeedFetchService, service.NewContentItemService, service.NewTagService, service.NewFolderService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewFeedHandler, handler.NewContentItemHandler, handler.NewTagHandler, handler.NewFolderHandler)

var jobSet = wire.NewSet(job.NewJob, job.NewUserJob)

var serverSet = wire.NewSet(server.NewHTTPServer, server.NewJobServer)

// build App
func newApp(
	httpServer *http.Server,
	jobServer *server.JobServer,

) *app.App {
	return app.NewApp(app.WithServer(httpServer, jobServer), app.WithName("shiliu-server"))
}
