// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/content-items": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "统一内容列表查询入口，支持关键词搜索、内容类型、处理状态、内容标记和订阅源单值 AND 过滤",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "内容条目模块"
                ],
                "summary": "查询统一内容条目列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "content type: text/audio",
                        "name": "content_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "processing status: unprocessed/completed",
                        "name": "processing_status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "content mark: later/favorite",
                        "name": "mark",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "feed id",
                        "name": "feed_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search keyword",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.ListContentItemsResponse"
                        }
                    }
                }
            }
        },
        "/content-items/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "返回单条内容条目的详情与安全渲染字段",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "内容条目模块"
                ],
                "summary": "查询内容条目详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "content item id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.GetContentItemResponse"
                        }
                    }
                }
            }
        },
        "/content-items/{id}/audio-progress": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "仅持久化音频型内容条目的播放位置，不持久化文本阅读位置，也不改变处理状态。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "内容条目模块"
                ],
                "summary": "更新音频播放进度",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "content item id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "audio progress seconds",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateContentItemAudioProgressRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.GetContentItemResponse"
                        }
                    }
                }
            }
        },
        "/content-items/{id}/marks/{mark}": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "独立设置或取消稍后处理、收藏标记，不改变处理状态或消费进度。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "内容条目模块"
                ],
                "summary": "更新内容条目标记",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "content item id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "content mark: later/favorite",
                        "name": "mark",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "content mark state",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateContentItemMarkRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.GetContentItemResponse"
                        }
                    }
                }
            }
        },
        "/content-items/{id}/processing-status": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "手动在未处理和已完成之间切换内容条目的处理状态，不改变内容标记或消费进度。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "内容条目模块"
                ],
                "summary": "更新内容条目处理状态",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "content item id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "processing status",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateContentItemProcessingStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.GetContentItemResponse"
                        }
                    }
                }
            }
        },
        "/content-views/completed": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Completed view presets processing_status=completed and accepts additional single-value filters.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Content item module"
                ],
                "summary": "List completed content items",
                "parameters": [
                    {
                        "type": "string",
                        "description": "content type: text/audio",
                        "name": "content_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "content mark: later/favorite",
                        "name": "mark",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "feed id",
                        "name": "feed_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search keyword",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.ListContentItemsResponse"
                        }
                    }
                }
            }
        },
        "/content-views/favorite": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Favorite view presets mark=favorite and accepts additional single-value filters.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Content item module"
                ],
                "summary": "List favorite content items",
                "parameters": [
                    {
                        "type": "string",
                        "description": "content type: text/audio",
                        "name": "content_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "processing status: unprocessed/completed",
                        "name": "processing_status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "feed id",
                        "name": "feed_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search keyword",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.ListContentItemsResponse"
                        }
                    }
                }
            }
        },
        "/content-views/inbox": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Inbox view presets processing_status=unprocessed and accepts additional single-value filters.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Content item module"
                ],
                "summary": "List inbox content items",
                "parameters": [
                    {
                        "type": "string",
                        "description": "content type: text/audio",
                        "name": "content_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "content mark: later/favorite",
                        "name": "mark",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "feed id",
                        "name": "feed_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search keyword",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.ListContentItemsResponse"
                        }
                    }
                }
            }
        },
        "/content-views/later": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Later view presets mark=later and accepts additional single-value filters.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Content item module"
                ],
                "summary": "List later content items",
                "parameters": [
                    {
                        "type": "string",
                        "description": "content type: text/audio",
                        "name": "content_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "processing status: unprocessed/completed",
                        "name": "processing_status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "feed id",
                        "name": "feed_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search keyword",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.ListContentItemsResponse"
                        }
                    }
                }
            }
        },
        "/feeds": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "返回所有订阅源及其当前 / 最后抓取状态、类型和所属文件夹",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "订阅源模块"
                ],
                "summary": "查询订阅源列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.ListFeedsResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "抓取并解析成功后创建订阅源，按规范化 feed URL 去重",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "订阅源模块"
                ],
                "summary": "添加订阅源",
                "parameters": [
                    {
                        "description": "params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreateFeedRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.CreateFeedResponse"
                        }
                    }
                }
            }
        },
        "/feeds/refresh": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "逐个复用抓取 service 刷新全部订阅源；同源抓取进行中时返回 skipped 语义",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "订阅源模块"
                ],
                "summary": "手动刷新全部订阅源",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.RefreshFeedsResponse"
                        }
                    }
                }
            }
        },
        "/feeds/{id}": {
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "删除订阅源并级联删除其内容条目及派生数据",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "订阅源模块"
                ],
                "summary": "删除订阅源",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "feed id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Response"
                        }
                    }
                }
            }
        },
        "/feeds/{id}/content-items": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Feed detail view presets feed_id from the path and accepts additional single-value filters.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Content item module"
                ],
                "summary": "List feed content items",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "feed id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "content type: text/audio",
                        "name": "content_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "processing status: unprocessed/completed",
                        "name": "processing_status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "content mark: later/favorite",
                        "name": "mark",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search keyword",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.ListContentItemsResponse"
                        }
                    }
                }
            }
        },
        "/feeds/{id}/refresh": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "复用抓取 service 刷新单个订阅源；同源抓取进行中时返回 skipped 语义",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "订阅源模块"
                ],
                "summary": "手动刷新单个订阅源",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "feed id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.RefreshFeedResponse"
                        }
                    }
                }
            }
        },
        "/initialization": {
            "get": {
                "description": "返回拾流单实例是否已经创建唯一用户账户",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "查询首次初始化状态",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.InitializationStatusResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "尚无用户账户时创建唯一用户账户，成功后入口永久关闭",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "首次初始化",
                "parameters": [
                    {
                        "description": "params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.InitializeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Response"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "账号登录",
                "parameters": [
                    {
                        "description": "params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.LoginResponse"
                        }
                    }
                }
            }
        },
        "/user": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "获取用户信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.GetProfileResponse"
                        }
                    }
                }
            }
        },
        "/user/password": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "已登录用户使用旧密码修改为新密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "修改当前用户密码",
                "parameters": [
                    {
                        "description": "params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.ChangePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "v1.ChangePasswordRequest": {
            "type": "object",
            "required": [
                "newPassword",
                "oldPassword"
            ],
            "properties": {
                "newPassword": {
                    "type": "string",
                    "maxLength": 72,
                    "minLength": 12,
                    "example": "1234567890123"
                },
                "oldPassword": {
                    "type": "string",
                    "example": "123456789012"
                }
            }
        },
        "v1.ContentItemDetailResponseData": {
            "type": "object",
            "properties": {
                "audioProgressSeconds": {
                    "type": "integer"
                },
                "availableText": {
                    "type": "string"
                },
                "contentSafe": {
                    "type": "string"
                },
                "contentType": {
                    "type": "string",
                    "example": "text"
                },
                "descriptionSafe": {
                    "type": "string"
                },
                "favorited": {
                    "type": "boolean"
                },
                "feedId": {
                    "type": "integer"
                },
                "fetchedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "markedLater": {
                    "type": "boolean"
                },
                "processingStatus": {
                    "type": "string",
                    "example": "unprocessed"
                },
                "publishedAt": {
                    "type": "string"
                },
                "showNotesSafe": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "v1.ContentItemListItemData": {
            "type": "object",
            "properties": {
                "audioProgressSeconds": {
                    "type": "integer"
                },
                "availableText": {
                    "type": "string"
                },
                "contentType": {
                    "type": "string",
                    "example": "text"
                },
                "favorited": {
                    "type": "boolean"
                },
                "feedId": {
                    "type": "integer"
                },
                "fetchedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "markedLater": {
                    "type": "boolean"
                },
                "processingStatus": {
                    "type": "string",
                    "example": "unprocessed"
                },
                "publishedAt": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "v1.CreateFeedRequest": {
            "type": "object",
            "required": [
                "feedUrl"
            ],
            "properties": {
                "feedUrl": {
                    "type": "string",
                    "example": "https://example.com/feed.xml"
                }
            }
        },
        "v1.CreateFeedResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/v1.CreateFeedResponseData"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "v1.CreateFeedResponseData": {
            "type": "object",
            "properties": {
                "feedUrl": {
                    "type": "string"
                },
                "fetchedItems": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "insertedItems": {
                    "type": "integer"
                },
                "type": {
                    "type": "string",
                    "example": "rss"
                }
            }
        },
        "v1.FeedResponseData": {
            "type": "object",
            "properties": {
                "feedUrl": {
                    "type": "string"
                },
                "fetchStatus": {
                    "type": "string",
                    "example": "success"
                },
                "folderId": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "lastFetchError": {
                    "type": "string"
                },
                "lastFetchedAt": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "example": "rss"
                }
            }
        },
        "v1.GetContentItemResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/v1.ContentItemDetailResponseData"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "v1.GetProfileResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/v1.GetProfileResponseData"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "v1.GetProfileResponseData": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string",
                    "example": "shiliu"
                }
            }
        },
        "v1.InitializationStatusResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/v1.InitializationStatusResponseData"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "v1.InitializationStatusResponseData": {
            "type": "object",
            "properties": {
                "initialized": {
                    "type": "boolean"
                }
            }
        },
        "v1.InitializeRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "123456789012"
                },
                "username": {
                    "type": "string",
                    "example": "shiliu"
                }
            }
        },
        "v1.ListContentItemsResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/v1.ListContentItemsResponseData"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "v1.ListContentItemsResponseData": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.ContentItemListItemData"
                    }
                },
                "page": {
                    "$ref": "#/definitions/v1.PageMeta"
                }
            }
        },
        "v1.ListFeedsResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/v1.ListFeedsResponseData"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "v1.ListFeedsResponseData": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.FeedResponseData"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "v1.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "123456789012"
                },
                "username": {
                    "type": "string",
                    "example": "shiliu"
                }
            }
        },
        "v1.LoginResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/v1.LoginResponseData"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "v1.LoginResponseData": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                }
            }
        },
        "v1.PageMeta": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "v1.RefreshFeedResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/v1.RefreshFeedResponseData"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "v1.RefreshFeedResponseData": {
            "type": "object",
            "properties": {
                "feedId": {
                    "type": "integer"
                },
                "feedUrl": {
                    "type": "string"
                },
                "fetchedItems": {
                    "type": "integer"
                },
                "insertedItems": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "skippedExistingItems": {
                    "type": "integer"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "v1.RefreshFeedsResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/v1.RefreshFeedsResponseData"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "v1.RefreshFeedsResponseData": {
            "type": "object",
            "properties": {
                "failed": {
                    "type": "integer"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.RefreshFeedResponseData"
                    }
                },
                "refreshed": {
                    "type": "integer"
                },
                "skipped": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "v1.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "v1.UpdateContentItemAudioProgressRequest": {
            "type": "object",
            "required": [
                "audioProgressSeconds"
            ],
            "properties": {
                "audioProgressSeconds": {
                    "type": "integer"
                }
            }
        },
        "v1.UpdateContentItemMarkRequest": {
            "type": "object",
            "required": [
                "marked"
            ],
            "properties": {
                "marked": {
                    "type": "boolean"
                }
            }
        },
        "v1.UpdateContentItemProcessingStatusRequest": {
            "type": "object",
            "required": [
                "processingStatus"
            ],
            "properties": {
                "processingStatus": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8000",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Nunu Example API",
	Description:      "This is a sample server celler server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
